import {expect,test} from '@playwright/test'
test('public demo controls and routes work',async({page},testInfo)=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Command Center'})).toBeVisible()
 if(testInfo.project.name==='mobile'){await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByLabel('Primary navigation')).toBeVisible();await page.getByRole('button',{name:'Close navigation'}).click()}
 await page.getByRole('button',{name:'View data boundary'}).click();await expect(page.getByRole('dialog',{name:'The public / private boundary'})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click()
 await page.getByRole('button',{name:'Explain ranking'}).click();await expect(page.getByRole('dialog',{name:/Northstar Collection/})).toContainText('Weighted result');await page.getByRole('button',{name:'Close drawer'}).click()
 await page.getByRole('button',{name:/Search/}).click();await page.getByPlaceholder(/Search assets/).fill('Bridgewater');await expect(page.getByRole('button',{name:/Bridgewater Associates/})).toBeVisible()
})
test('institution universe uses real public-source identities',async({page})=>{await page.goto('/universes');await expect(page.getByRole('heading',{name:'Institutional Universes'})).toBeVisible();await page.getByRole('button',{name:'Venture Capital',exact:true}).click();await expect(page.getByRole('heading',{name:'Sequoia Capital'})).toBeVisible();await expect(page.getByRole('link',{name:/Open official source/}).first()).toHaveAttribute('href',/^https:/)})
test('keyboard focus and dialog semantics are usable',async({page})=>{await page.goto('/');const boundary=page.getByRole('button',{name:'View data boundary'});await boundary.focus();await expect(boundary).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toHaveAttribute('aria-modal','true');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)})
test('guided demo and counsel acknowledgement persist across routes',async({page})=>{
 await page.goto('/');await page.evaluate(()=>localStorage.removeItem('pmos-demo-v1'));await page.reload()
 await page.getByRole('button',{name:'Guided demo'}).click()
 await expect(page.getByRole('dialog',{name:'Guided demo'})).toContainText('STEP 1 OF 6')
 await page.getByRole('link',{name:/Show me/}).click()
 await expect(page.getByRole('dialog',{name:'Guided demo'})).toContainText('STEP 2 OF 6')
 await page.getByRole('link',{name:/Show me/}).click()
 await expect(page).toHaveURL(/\/evidence/)
 await expect(page.getByRole('dialog',{name:'Guided demo'})).toContainText('STEP 2 OF 6')
 await page.getByRole('dialog',{name:'Guided demo'}).getByRole('button',{name:'Continue as Counsel'}).click()
 await page.getByRole('dialog',{name:'Enter a synthetic demo role'}).getByRole('button',{name:'Continue as Counsel'}).click()
 await page.getByRole('button',{name:'Acknowledge exception'}).click()
 await expect(page.getByRole('button',{name:'Acknowledged by counsel'})).toBeDisabled()
 await page.reload()
 await expect(page.getByRole('button',{name:'Acknowledged by counsel'})).toBeDisabled()
 await expect(page.getByRole('dialog',{name:'Guided demo'})).toContainText('STEP 3 OF 6')
})
test('relationship graph exposes working landscape horizontal controls',async({page})=>{
 await page.setViewportSize({width:844,height:390});await page.goto('/relationships')
 const graph=page.getByLabel('Scrollable relationship graph')
 await expect(graph).toBeVisible()
 const before=await graph.evaluate(element=>element.scrollLeft)
 await page.getByRole('button',{name:'Scroll relationship graph right'}).click()
 await expect.poll(()=>graph.evaluate(element=>element.scrollLeft)).toBeGreaterThan(before)
 await expect(page.getByText(/keep your natural orientation/i)).toBeVisible()
})
test('mobile landscape navigation keeps routes and footer controls separated',async({page})=>{
 await page.setViewportSize({width:844,height:390});await page.goto('/deal-room')
 await page.getByRole('button',{name:'Open navigation'}).click()
 const drawer=page.getByLabel('Primary navigation')
 await expect(drawer).toBeVisible()
 await expect(drawer.getByRole('link',{name:'Opportunities'})).toBeVisible()
 await expect(drawer.getByText('Private Sales',{exact:true})).toBeVisible()
 await expect(drawer.getByRole('button',{name:/Private intelligence sealed/})).toBeVisible()
 const routes=await drawer.locator('nav').boundingBox(),footer=await drawer.locator('.drawerFoot').boundingBox()
 expect(routes&&footer&&routes.y+routes.height<=footer.y).toBeTruthy()
 await drawer.getByRole('link',{name:'Relationships'}).click()
 await expect(page).toHaveURL(/\/relationships/)
 await expect(drawer).not.toHaveClass(/mobileOpen/)
})
test('public verification queue exposes human claim decisions',async({page})=>{
 await page.goto('/verification');await expect(page.getByRole('heading',{name:'Verification Queue'})).toBeVisible()
 const synthetic=page.getByRole('heading',{name:'Synthetic collector mandate'}).locator('xpath=ancestor::article')
 await expect(synthetic).toContainText('HUMAN_REVIEW_REQUIRED')
 await synthetic.getByRole('button',{name:'Reject'}).click()
 await expect(synthetic).toContainText('REJECTED')
})
