'use client'
import Link from 'next/link'
import {usePathname,useRouter} from 'next/navigation'
import {useEffect,useMemo,useRef,useState} from 'react'
import {Archive,ArrowLeft,ArrowRight,ArrowsLeftRight,Buildings,CheckCircle,DeviceMobile,FileArrowDown,FileMagnifyingGlass,FlowArrow,List,MagnifyingGlass,Presentation,ShieldCheck,SignIn,TrendUp,Users,X,Warning} from '@phosphor-icons/react'
import {evidence,graphNodes,institutions as institutionData,ranking,searchItems} from '../lib/demo-data'
import {useDemoState} from '../lib/demo-state'

type View='command'|'evidence'|'deal'|'universes'|'relationships'|'opportunities'
const nav=[['Command Center','/',FlowArrow],['Evidence Room','/evidence',FileMagnifyingGlass],['Deal Room','/deal-room',Archive],['Relationships','/relationships',Users],['Institutional Universes','/universes',Buildings],['Opportunities','/opportunities',TrendUp]] as const
const tour=[{title:'Transaction readiness',body:'Start with the five critical evidence gates.',href:'/#readiness'},{title:'Restitution exception',body:'Open the evidence room, continue as Counsel, then acknowledge the custody-gap review.',href:'/evidence#restitution'},{title:'Collector ranking',body:'Inspect every factor behind the leading synthetic collector score.',href:'/#ranking'},{title:'Relationship path',body:'Select graph nodes for evidence. On a phone, swipe sideways or use the arrow controls—rotation is optional.',href:'/relationships#relationship-graph'},{title:'Capital universe',body:'Browse real institutions supported only by public evidence.',href:'/universes'},{title:'Deal room',body:'Close with readiness gates, counsel notes and audit history.',href:'/deal-room'}]

function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){
 const ref=useRef<HTMLButtonElement>(null)
 useEffect(()=>{ref.current?.focus();const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onClose])
 return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`dialog ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="dialogHead"><div><p className="eyebrow">PMOS · PUBLIC DEMONSTRATION</p><h2 id="dialog-title">{title}</h2></div><button ref={ref} className="iconButton" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</section></div>
}
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay drawerOverlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label={title}><div className="dialogHead"><div><p className="eyebrow">EXPLAINABILITY</p><h2>{title}</h2></div><button className="iconButton" onClick={onClose} aria-label="Close drawer"><X size={20}/></button></div>{children}</aside></div>}

export default function PmosApp({view='command'}:{view?:View}){
 const path=usePathname(),router=useRouter(),{state,setState,log}=useDemoState()
 const [mobile,setMobile]=useState(false),[modal,setModal]=useState<string|null>(null),[rank,setRank]=useState<(typeof ranking)[number]|null>(null),[node,setNode]=useState<(typeof graphNodes)[number]|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('All')
 const tourStep=Math.min(state.tourStep,tour.length-1)
 const results=useMemo(()=>query.trim()?searchItems.filter(x=>(x.name+' '+x.type+' '+x.meta).toLowerCase().includes(query.toLowerCase())).slice(0,10):searchItems.slice(0,8),[query])
 const visibleInstitutions=category==='All'?institutionData:institutionData.filter(x=>x.category===category)
 const exportBrief=()=>{const body=`PMOS SYNTHETIC TRANSACTION BRIEF\n\nOpportunity: PM-2026-014\nAsset: Untitled, 1988 (fictional)\nReadiness: 82/100 — PASS WITH EXCEPTIONS\nOpen exception: Synthetic restitution review\n\nThis document contains synthetic transaction data only. Real institutions shown elsewhere in PMOS are sourced from public first-party pages; no private contacts or proprietary intelligence are included.`;const url=URL.createObjectURL(new Blob([body],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='PMOS-synthetic-transaction-brief.txt';a.click();URL.revokeObjectURL(url);log('Synthetic transaction brief exported')}
 const signIn=(role:'Specialist'|'Counsel')=>{setState(s=>({...s,role,audit:[{at:new Date().toISOString().slice(0,16).replace('T',' '),action:`Demo role changed to ${role}`,actor:role},...s.audit]}));setModal(null)}
 return <div className="app">
  <aside className={`side ${mobile?'mobileOpen':''}`} aria-label="Primary navigation"><div className="lockup"><span className="mark">P</span><div><b>PMOS</b><small>Private Markets OS</small></div><button className="sideClose" onClick={()=>setMobile(false)} aria-label="Close navigation"><X size={20}/></button></div><nav>{nav.map(([label,href,Icon])=><Link key={href} href={href} onClick={()=>setMobile(false)} className={path===href?'active':''}><Icon size={16}/>{label}</Link>)}</nav><div className="verticalSwitch"><small>ACTIVE VERTICAL</small><b>Private Sales</b><Link href="/universes">Explore capital intelligence →</Link></div><button className="safe" onClick={()=>setModal('boundary')}><ShieldCheck size={18}/><span><small>PUBLIC DEMO</small><b>Private intelligence sealed</b></span></button></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Dismiss navigation overlay"/>}
  <main><header><button className="mobileMenu" onClick={()=>setMobile(true)} aria-expanded={mobile} aria-label="Open navigation"><List size={20}/></button><div className="pageTitle"><p className="eyebrow">PRIVATE SALES · SYNTHETIC TRANSACTION</p><h1>{view==='command'?'Command Center':view==='evidence'?'Evidence Room':view==='deal'?'Private Deal Room':view==='universes'?'Institutional Universes':view==='relationships'?'Relationship Intelligence':'Opportunities'}</h1></div><div className="actions"><button className="searchAction" aria-label="Search" onClick={()=>setModal('search')}><MagnifyingGlass size={15}/><span>Search</span></button><button className="exportAction" aria-label="Export brief" onClick={exportBrief}><FileArrowDown size={15}/><span>Export brief</span></button><button className="primary guideAction" aria-label="Guided demo" onClick={()=>setState(s=>({...s,guided:true,tourStep:0}))}><Presentation size={15}/><span>Guided demo</span></button></div></header>
  <section className="notice"><span>PUBLIC-SAFE DEMO</span><p>The transaction is fictional. Named institutions are real and shown with public-source identity only.</p><button onClick={()=>setModal('boundary')}>View data boundary</button></section>
  {view==='command'&&<CommandCenter onRank={setRank} onNode={setNode} onEvidence={()=>router.push('/evidence')} onDeal={()=>router.push('/deal-room')}/>} 
  {view==='evidence'&&<EvidenceRoom role={state.role} acknowledged={state.acknowledgedExceptions.includes('restitution')} onSignIn={()=>setModal('signin')} onAcknowledge={()=>setState(s=>s.acknowledgedExceptions.includes('restitution')?s:{...s,acknowledgedExceptions:[...s.acknowledgedExceptions,'restitution'],audit:[{at:new Date().toISOString().slice(0,16).replace('T',' '),action:'Restitution exception acknowledged by counsel',actor:s.role},...s.audit]})}/>}
  {view==='deal'&&<DealRoom role={state.role} audit={state.audit} onSignIn={()=>setModal('signin')} log={log}/>} 
  {view==='universes'&&<Universes category={category} setCategory={setCategory} institutions={visibleInstitutions}/>} 
  {view==='relationships'&&<Relationships onNode={setNode}/>} 
  {view==='opportunities'&&<Opportunities/>}
  </main>
  {modal==='boundary'&&<Modal title="The public / private boundary" onClose={()=>setModal(null)}><div className="boundaryGrid"><article><ShieldCheck size={24}/><h3>Public showcase</h3><p>Application code, real institution names from official public pages, synthetic transactions, generic scores, and synthetic relationship paths.</p></article><article className="privateCard"><Warning size={24}/><h3>Never public</h3><p>Private contacts, auction-house contact intelligence, investor records, notes, introductions, outreach, private scoring, evidence files, credentials, or local databases.</p></article></div><p className="callout">The deployed site has no route, API, environment variable, or browser bundle capable of reading the local private datastore.</p></Modal>}
  {modal==='search'&&<Modal title="Search the public-safe graph" onClose={()=>setModal(null)} wide><label className="searchBox"><MagnifyingGlass size={20}/><span className="srOnly">Search assets and institutions</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets, opportunities, VC, PE, hedge funds, sovereigns…"/></label><div className="searchResults">{results.map(x=><button key={x.type+x.name} onClick={()=>{router.push(x.href);setModal(null)}}><span>{x.type}</span><b>{x.name}</b><small>{x.meta}</small><ArrowRight size={16}/></button>)}</div></Modal>}
  {modal==='signin'&&<Modal title="Enter a synthetic demo role" onClose={()=>setModal(null)}><p>Public browsing remains open. Decision actions require a role so the audit trail can show who acted.</p><div className="roleButtons"><button onClick={()=>signIn('Specialist')}><SignIn size={18}/> Continue as Specialist</button><button onClick={()=>signIn('Counsel')}><SignIn size={18}/> Continue as Counsel</button></div><small className="muted">This is demonstration authentication, not access to private intelligence.</small></Modal>}
  {rank&&<Drawer title={`${rank.name} · ${rank.fit} fit`} onClose={()=>setRank(null)}><p className="drawerIntro">Transparent synthetic scoring. Each factor is inspectable and no score implies a real relationship.</p>{rank.factors.map(([name,value])=><div className="factor" key={name}><div><b>{name}</b><span>{value}/100</span></div><div className="factorBar"><i style={{width:`${value}%`}}/></div></div>)}<div className="formula"><b>Weighted result</b><p>Collection fit 30% · mandate 25% · relationship path 20% · evidence 15% · contactability 10%</p></div></Drawer>}
  {node&&<Drawer title={node.name} onClose={()=>setNode(null)}><span className="statusTag">{node.type}</span><p className="drawerIntro">{node.detail}</p><h3>Relationship evidence</h3><div className="evidenceMini"><b>{node.id==='capital'?'Public identity only':'Synthetic relationship assertion'}</b><p>{node.id==='capital'?'No transaction involvement or relationship is asserted.':'Supported inside the fictional demonstration scenario.'}</p><span>Confidence {node.id==='capital'?'98':'87'}% · reviewed Aug 2026</span></div></Drawer>}
  {state.guided&&<div className="tour" role="dialog" aria-label="Guided demo"><div><span>STEP {tourStep+1} OF {tour.length}</span><h3>{tour[tourStep].title}</h3><p>{tour[tourStep].body}</p></div><div className="tourActions">{tourStep>0&&<button aria-label="Previous guided demo step" onClick={()=>setState(s=>({...s,tourStep:Math.max(0,s.tourStep-1)}))}><ArrowLeft size={14}/> Back</button>}<button onClick={()=>setState(s=>({...s,guided:false,tourStep:0}))}>Exit</button>{tourStep===1&&path.startsWith('/evidence')?(state.role!=='Counsel'?<button className="tourPrimary" onClick={()=>setModal('signin')}><SignIn size={14}/> Continue as Counsel</button>:!state.acknowledgedExceptions.includes('restitution')?<button className="tourPrimary" onClick={()=>setState(s=>({...s,tourStep:2,acknowledgedExceptions:[...s.acknowledgedExceptions,'restitution'],audit:[{at:new Date().toISOString().slice(0,16).replace('T',' '),action:'Restitution exception acknowledged by counsel',actor:s.role},...s.audit]}))}><CheckCircle size={14}/> Acknowledge exception</button>:<button className="tourPrimary" onClick={()=>setState(s=>({...s,tourStep:2}))}>Continue <ArrowRight size={14}/></button>):<Link href={tour[tourStep].href} onClick={()=>setState(s=>tourStep===1?s:tourStep<tour.length-1?{...s,tourStep:tourStep+1}:{...s,guided:false,tourStep:0})}>{tourStep===tour.length-1?'Finish':'Show me'} <ArrowRight size={14}/></Link>}</div></div>}
 </div>
}

function CommandCenter({onRank,onNode,onEvidence,onDeal}:{onRank:(x:(typeof ranking)[number])=>void;onNode:(x:(typeof graphNodes)[number])=>void;onEvidence:()=>void;onDeal:()=>void}){return <><section className="deal"><div><p className="eyebrow light">PRIVATE SALE · PM-2026-014</p><h2>Untitled, 1988</h2><p>Post-war & contemporary · Fictional artist · Oil and mixed media on canvas</p><div className="dealmeta"><span>Indicative value <b>$18–24M</b></span><span>Stage <b>Specialist review</b></span><span>Owner <b>Private Sales</b></span></div></div><div className="readiness"><div className="ring"><strong>82</strong><small>/ 100</small></div><div><b>Private sale readiness</b><p>4 of 5 critical gates supported</p><button onClick={onDeal}>PASS — EXCEPTIONS <ArrowRight size={12}/></button></div></div></section><section className="metrics"><article><small>Evidence completeness</small><b>87%</b><div className="bar"><i style={{width:'87%'}}/></div><p>34 of 39 required items</p></article><article><small>Collector matches</small><b>12</b><p><span className="up">+3</span> since last review</p></article><article><small>Open exceptions</small><b>3</b><p>1 requires counsel</p></article><article><small>Capital universes</small><b>8</b><p>Real institutions · public sources</p></article></section><div className="columns"><section className="panel" id="readiness"><div className="panelhead"><div><p className="eyebrow">EXCEPTION ENGINE</p><h3>Transaction readiness</h3></div><button onClick={onEvidence}>View all evidence <ArrowRight size={13}/></button></div>{evidence.map(x=><button className="check" key={x.id} onClick={onEvidence}><span className={`state ${x.state.includes('REVIEW')?'warn':'ok'}`}>{x.state.includes('REVIEW')?<Warning/>:<CheckCircle/>}</span><div><b>{x.title}</b><p>{x.decision}</p></div><label className={x.state.includes('REVIEW')?'amber':'green'}>{x.state}</label></button>)}</section><section className="panel" id="ranking"><div className="panelhead"><div><p className="eyebrow">COLLECTOR MATCH</p><h3>Highest-fit counterparties</h3></div><button onClick={()=>onRank(ranking[0])}>Explain ranking</button></div>{ranking.map((x,n)=><button className="buyer" key={x.id} onClick={()=>onRank(x)}><span className="avatar">{n+1}</span><div className="buyerinfo"><b>{x.name}</b><small>{x.region}</small><p>Inspect score factors and evidence</p></div><div className="fit"><strong>{x.fit}</strong><small>FIT</small><span>{x.status}</span></div></button>)}</section></div><Graph onNode={onNode}/></>}

function Graph({onNode}:{onNode:(x:(typeof graphNodes)[number])=>void}){const graphRef=useRef<HTMLDivElement>(null);const scroll=(direction:number)=>graphRef.current?.scrollBy({left:direction*Math.max(240,graphRef.current.clientWidth*.7),behavior:'smooth'});return <section className="panel graph" id="relationship-graph"><div className="panelhead"><div><p className="eyebrow">RELATIONSHIP GRAPH</p><h3>Evidence-backed transaction path</h3></div><span className="legend">Select any node to inspect its evidence</span></div><div className="graphGuide"><span><DeviceMobile size={17}/><b>Phone tip:</b> keep your natural orientation and swipe sideways to explore.</span><div><button aria-label="Scroll relationship graph left" onClick={()=>scroll(-1)}><ArrowLeft size={15}/></button><button aria-label="Scroll relationship graph right" onClick={()=>scroll(1)}><ArrowRight size={15}/></button></div></div><div className="graphline" ref={graphRef} tabIndex={0} aria-label="Scrollable relationship graph"><span className="srOnly"><ArrowsLeftRight/> Scroll horizontally to inspect all nodes.</span>{graphNodes.map((x,i)=><div className="graphPart" key={x.id}>{i>0&&<span>{['authority','advised by','introduces','capital context'][i-1]}</span>}<button className={`node ${x.id==='asset'?'asset':x.id==='capital'?'gold':''}`} onClick={()=>onNode(x)}><small>{x.type}</small><b>{x.name}</b></button></div>)}</div><p className="caption">Real institutions appear only as public context unless an evidence-backed public relationship exists. The fictional deal does not assert their involvement.</p></section>}

function EvidenceRoom({role,acknowledged,onSignIn,onAcknowledge}:{role:string;acknowledged:boolean;onSignIn:()=>void;onAcknowledge:()=>void}){return <div className="pageGrid"><section className="panel full"><div className="panelhead"><div><p className="eyebrow">CLAIM PROVENANCE</p><h3>Five critical evidence gates</h3></div><span className="statusTag">34 / 39 items supported</span></div><div className="evidenceTable">{evidence.map(x=><article id={x.id} key={x.id}><div className="evidenceTitle"><span className={`state ${x.state.includes('REVIEW')?'warn':'ok'}`}>{x.state.includes('REVIEW')?<Warning/>:<CheckCircle/>}</span><div><h3>{x.title}</h3><p>{x.source}</p></div></div><dl><div><dt>Confidence</dt><dd>{x.confidence}%</dd></div><div><dt>Freshness</dt><dd>{x.freshness}</dd></div><div><dt>Conflict</dt><dd>{x.conflict}</dd></div><div><dt>Decision</dt><dd>{x.decision}</dd></div></dl>{x.id==='restitution'&&<button className={acknowledged?'acknowledged':'primary'} disabled={acknowledged} onClick={()=>role==='Counsel'?onAcknowledge():onSignIn()}>{acknowledged?<><CheckCircle size={16}/> Acknowledged by counsel</>:role==='Counsel'?'Acknowledge as counsel':'Counsel sign-in required'}</button>}</article>)}</div></section></div>}

function DealRoom({role,audit,onSignIn,log}:{role:string;audit:{at:string;action:string;actor:string}[];onSignIn:()=>void;log:(x:string)=>void}){return <div className="dealRoom"><section className="panel"><div className="panelhead"><div><p className="eyebrow">READINESS GATES</p><h3>Closing control</h3></div><span className="amber statusTag">PASS — EXCEPTIONS</span></div>{evidence.map(x=><div className="gate" key={x.id}><span>{x.state.includes('REVIEW')?'!':'✓'}</span><div><b>{x.title}</b><small>{x.decision}</small></div></div>)}<button className="primary fullButton" onClick={()=>role==='Public viewer'?onSignIn():log('Closing package marked ready for specialist review')}>Mark ready for specialist review</button></section><section className="panel"><div className="panelhead"><div><p className="eyebrow">COUNSEL / REVIEW</p><h3>Restitution escalation</h3></div><span className="statusTag">OPEN</span></div><div className="callout"><b>Synthetic custody gap · 1939–1946</b><p>Specialist requests counsel review before buyer engagement. No real artwork, owner, or claim is represented.</p></div><label className="notes"><span>Review note</span><textarea defaultValue="Confirm scope of loss-register search; request original 1998 invoice."/></label><button onClick={()=>role==='Counsel'?log('Counsel note saved'):onSignIn()}>{role==='Counsel'?'Save counsel note':'Sign in as counsel'}</button></section><section className="panel auditPanel"><div className="panelhead"><div><p className="eyebrow">AUDIT HISTORY</p><h3>Immutable demonstration log</h3></div><span className="statusTag">{role}</span></div>{audit.map((x,i)=><div className="auditRow" key={x.at+x.action+i}><span>{x.at}</span><b>{x.action}</b><small>{x.actor}</small></div>)}</section></div>}

function Universes({category,setCategory,institutions}:{category:string;setCategory:(x:string)=>void;institutions:typeof institutionData}){const cats=['All','Venture Capital','Private Equity','Hedge Fund','Sovereign Wealth','Corporate Venture Capital','Pension','Private Bank'];return <><section className="universeHero"><div><p className="eyebrow">GLOBAL CAPITAL INTELLIGENCE</p><h2>Real institutions. Public evidence. Explicit limits.</h2><p>PMOS maps how capital institutions may relate to markets and opportunities. No private contact, relationship, or transaction is implied.</p></div><div><b>16</b><span>public-source profiles</span></div></section><div className="filters" role="group" aria-label="Filter institutions">{cats.map(x=><button key={x} className={category===x?'active':''} onClick={()=>setCategory(x)}>{x}</button>)}</div><section className="institutionGrid">{institutions.map(x=><article key={x.id}><div className="institutionTop"><span>{x.category}</span><b>{x.confidence}%</b></div><h3>{x.name}</h3><p>{x.role}</p><dl><div><dt>Jurisdiction</dt><dd>{x.jurisdiction}</dd></div><div><dt>Location</dt><dd>{x.city}</dd></div><div><dt>Evidence</dt><dd>{x.sourceLabel}</dd></div></dl><div className="institutionFoot"><span>{x.freshness}</span><a href={x.source} target="_blank" rel="noreferrer">Open official source <ArrowRight size={12}/></a></div></article>)}</section></>}
function Relationships({onNode}:{onNode:(x:(typeof graphNodes)[number])=>void}){return <><section className="panel explanation"><p className="eyebrow">GRAPH SAFETY</p><h2>Relationship assertions require evidence.</h2><p>Blue nodes and edges belong to the fictional demonstration. Gold institutional nodes are real public identities; their presence does not assert a private relationship or participation in the transaction.</p></section><Graph onNode={onNode}/></>}
function Opportunities(){return <section className="opportunityGrid"><article className="panel"><span className="statusTag">PRIVATE SALE · SYNTHETIC</span><h2>Untitled, 1988</h2><p>A discreet private-sale readiness demonstration with evidence gates, exception management, ranking and audit history.</p><Link className="primaryLink" href="/deal-room">Open opportunity <ArrowRight size={14}/></Link></article><article className="panel"><span className="statusTag">VENTURE / CAPITAL MAP</span><h2>Institutional capital universe</h2><p>Real VC, PE, hedge fund, sovereign, pension, private-bank and CVC identities supported by first-party public pages.</p><Link className="primaryLink" href="/universes">Explore universe <ArrowRight size={14}/></Link></article></section>}
