from __future__ import annotations

import hashlib,json,os
from datetime import datetime,timedelta,timezone
from pathlib import Path
from urllib.parse import urlparse
from sqlalchemy import func,select

from .audit_ledger import append_ledger_event,verify_ledger
from .db import ControlAssuranceRun,CorroborationJob,Entity,EvidenceReviewAssignment,IdentityReviewAssignment,IncidentResponseExerciseRun,PrivateEgressReviewCase,PrivateSaleCase,RelationshipAssertion,RelationshipMentionReviewAssignment,RestoreDrillRun,RetentionAssessmentRun,ReviewerRosterAssessmentRun,SecurityReadinessRun

def _control(control,status,evidence,limitation):return {"control":control,"status":status,"evidence":evidence,"limitation":limitation}
def _aware(value):return value if value.tzinfo else value.replace(tzinfo=timezone.utc)

def build_security_readiness(session,repo_root:Path,technical:dict,environment:dict|None=None,backup_verified:bool=False)->dict:
    env=environment or dict(os.environ);now=datetime.now(timezone.utc);controls=[]
    repo=repo_root.resolve();db_path=Path(session.bind.url.database).resolve() if session.bind.url.database and session.bind.url.database!=":memory:" else None
    controls.append(_control("private_datastore_outside_public_repo","PROVEN" if db_path and repo not in db_path.parents else "FAIL",{"path_exposure":False},"File location only; host access controls remain separate."))
    private_pending=session.scalar(select(func.count()).select_from(CorroborationJob).join(Entity,Entity.id==CorroborationJob.entity_id).where(Entity.universe=="imported_private",CorroborationJob.status.in_({"PENDING","RETRY_REQUIRED"}))) or 0;open_egress_reviews=session.scalar(select(func.count()).select_from(PrivateEgressReviewCase).where(PrivateEgressReviewCase.status.not_in({"RESOLVED_NO_MATERIAL_DISCLOSURE","ESCALATED"}))) or 0;controls.append(_control("private_research_egress_boundary","PROVEN" if private_pending==0 and open_egress_reviews==0 else "CONTAINED_REVIEW_REQUIRED" if private_pending==0 else "FAIL",{"private_jobs_eligible_for_network":private_pending,"open_legacy_attempt_reviews":open_egress_reviews},"Imported-private entities cannot enter public web research. Historical attempts require accountable security review; containment is not retrospective approval."))
    controls.append(_control("public_release_safety","PROVEN" if technical.get("public_release_check") else "FAIL",{"gate_passed":bool(technical.get("public_release_check"))},"Proves the scanned Git history/worktree/client bundle at this run."))
    controls.append(_control("backend_security_tests","PROVEN" if technical.get("backend_tests") else "FAIL",{"gate_passed":bool(technical.get("backend_tests"))},"Test evidence is not live operating evidence."))
    controls.append(_control("public_web_build_and_browser_flows","PROVEN" if technical.get("web_build") and technical.get("browser_tests") else "FAIL",{"build_passed":bool(technical.get("web_build")),"browser_tests_passed":bool(technical.get("browser_tests"))},"Does not prove private API production deployment."))
    ledger=verify_ledger(session);controls.append(_control("append_only_audit_ledger","PROVEN" if ledger["valid"] else "FAIL",{"valid":ledger["valid"],"entries":ledger["entries"]},"SQLite trigger and hash-chain evidence; external immutable log retention remains unevidenced."))
    assurance=session.scalar(select(ControlAssuranceRun).order_by(ControlAssuranceRun.id.desc()));assurance_fresh=bool(assurance and assurance.status=="PASS" and _aware(assurance.created_at)>=now-timedelta(hours=24));controls.append(_control("private_control_assurance","PROVEN" if assurance_fresh else "FAIL",{"fresh_pass":assurance_fresh,"control_count":assurance.control_count if assurance else 0,"exception_count":assurance.exception_count if assurance else None},"Zero-population controls are design evidence, not exercised operating evidence."))
    controls.append(_control("verified_encrypted_backup","PROVEN" if backup_verified else "NOT_EVIDENCED",{"latest_backup_verified":backup_verified},"A backup is not a recovery drill."))
    auth_mode=env.get("PMOS_AUTH_MODE","disabled").casefold();issuer=env.get("PMOS_OIDC_ISSUER","");jwks=env.get("PMOS_OIDC_JWKS_URL","");aud=env.get("PMOS_OIDC_AUDIENCE","");tenant=env.get("PMOS_TENANT_ID","");oidc=auth_mode=="oidc" and urlparse(issuer).scheme=="https" and urlparse(jwks).scheme=="https" and urlparse(issuer).hostname==urlparse(jwks).hostname and bool(aud and tenant);controls.append(_control("production_oidc_mfa_tenant_configuration","CONFIGURED" if oidc else "NOT_CONFIGURED",{"auth_mode":auth_mode,"oidc_complete":oidc},"Configuration presence does not prove IdP policy or successful MFA integration testing."))
    exact_hosts=bool(env.get("PMOS_ALLOWED_HOSTS",""));controls.append(_control("private_api_network_edge","CONFIGURED" if exact_hosts and oidc else "NOT_CONFIGURED",{"exact_allowed_hosts":exact_hosts,"oidc_enabled":oidc},"Gateway WAF, distributed rate limiting, TLS termination, and egress isolation are not evidenced locally."))
    roster=session.scalar(select(ReviewerRosterAssessmentRun).order_by(ReviewerRosterAssessmentRun.id.desc()));roster_fresh=bool(roster and roster.status=="READY" and roster.roster_hash and _aware(roster.created_at)>=now-timedelta(days=30));controls.append(_control("reviewer_roster_configuration","CONFIGURED" if roster_fresh else "NOT_CONFIGURED",{"fresh_ready_roster":roster_fresh},"Configuration evidence does not prove active assignments or completed human review."))
    active_evidence=session.scalar(select(func.count()).select_from(EvidenceReviewAssignment).where(EvidenceReviewAssignment.status=="ACTIVE")) or 0;active_identity=session.scalar(select(func.count()).select_from(IdentityReviewAssignment).where(IdentityReviewAssignment.status=="ACTIVE")) or 0;active_mentions=session.scalar(select(func.count()).select_from(RelationshipMentionReviewAssignment).where(RelationshipMentionReviewAssignment.status=="ACTIVE")) or 0;controls.append(_control("reviewer_operating_assignments","OPERATING" if active_evidence+active_identity+active_mentions else "NOT_STAFFED",{"active_evidence_assignments":active_evidence,"active_identity_assignments":active_identity,"active_mention_assignments":active_mentions},"Named authorized human reviewers are required before adjudication."))
    verified_relationships=session.scalar(select(func.count()).select_from(RelationshipAssertion).where(RelationshipAssertion.status=="SPECIALIST_VERIFIED")) or 0;private_sales=session.scalar(select(func.count()).select_from(PrivateSaleCase)) or 0;controls.append(_control("transaction_workflow_operating_evidence","OPERATING" if verified_relationships and private_sales else "NOT_EXERCISED",{"verified_relationships":verified_relationships,"private_sale_cases":private_sales},"Synthetic UI flows do not prove private operating procedures."))
    retention=session.scalar(select(RetentionAssessmentRun).order_by(RetentionAssessmentRun.id.desc()));retention_fresh=bool(retention and _aware(retention.created_at)>=now-timedelta(hours=24));controls.append(_control("retention_and_deletion","DESIGN_ONLY" if retention_fresh else "NOT_EVIDENCED",{"fresh_assessment":retention_fresh,"assessment_status":retention.status if retention else None,"policy_configured":bool(retention and retention.policy_hash)},"Dry-run assessment and legal holds do not prove approved policy execution or defensible deletion."))
    drill=session.scalar(select(RestoreDrillRun).order_by(RestoreDrillRun.id.desc()));drill_fresh=bool(drill and drill.status=="PASS" and drill.sqlite_integrity=="ok" and drill.encrypted_storage_verified and drill.temporary_restore_removed and _aware(drill.completed_at)>=now-timedelta(days=90));controls.append(_control("restore_drill","PROVEN" if drill_fresh else "NOT_EVIDENCED",{"fresh_verified_drill":drill_fresh,"ledger_entries":drill.ledger_entries if drill else 0},"A local encrypted SQLite recovery drill does not prove disaster recovery for a future production PostgreSQL deployment."))
    exercise=session.scalar(select(IncidentResponseExerciseRun).order_by(IncidentResponseExerciseRun.id.desc()));exercise_fresh=bool(exercise and exercise.status=="PASS" and exercise.detection_count>=5 and exercise.containment_verified and exercise.recovery_verified and _aware(exercise.completed_at)>=now-timedelta(days=180));controls.append(_control("monitoring_and_incident_response","EXERCISED" if exercise_fresh else "NOT_EVIDENCED",{"fresh_release_leak_exercise":exercise_fresh,"detection_classes":exercise.detection_count if exercise else 0},"Proves local release-gate detection and containment only; external alert delivery, on-call response, and personnel timing remain unevidenced."))
    for name in ("external_security_review","gateway_rate_limit_and_waf"):
        controls.append(_control(name,"NOT_EVIDENCED",{},"Requires dated external or operational evidence; no self-attestation is accepted."))
    blocking={"FAIL","NOT_CONFIGURED","NOT_STAFFED","NOT_EXERCISED","NOT_EVIDENCED","DESIGN_ONLY","CONTAINED_REVIEW_REQUIRED"};status="PRODUCTION_READY" if all(x["status"] not in blocking for x in controls) else "NOT_PRODUCTION_READY"
    return {"classification":"PMOS PRIVATE AGGREGATE SECURITY READINESS — NO RECORD VALUES","generated_at":now.isoformat(),"status":status,"method":"fail_closed_v1","controls":controls,"summary":{state:sum(x["status"]==state for x in controls) for state in sorted({x["status"] for x in controls})}}

def persist_security_readiness(session,report:dict,actor:str="security-readiness-worker")->SecurityReadinessRun:
    canonical=json.dumps(report,sort_keys=True,separators=(",",":"),ensure_ascii=False);digest=hashlib.sha256(canonical.encode()).hexdigest();run=SecurityReadinessRun(status=report["status"],report_hash=digest,report_json=canonical,actor=actor);session.add(run);session.flush();append_ledger_event(session,"SECURITY_READINESS",run.id,actor,"SYSTEM","READINESS_RECORDED",{"status":run.status,"report_hash":digest,"summary":report["summary"]});return run
